package com.jbent.peoplecentral.template;

public class TemplateBuider {
	
	public static String buildViewTemplateCode(){
		String template = "<table>"
				+ "<tr><th>Attribute Name</th><th>Input Type</th><th>Value</th></tr>"
				+ "<tr th:each=\"avs : ${entity.getAttributeValueStorage()}\">"
				+ "<td th:text=\"${avs.name}\"></td>"
				+ "<td th:text=\"${avs.fieldTypeName}\"></td>"
				+ "<td th:text=\"${avs.getValue()}\"></td>"
				+ "</tr>"
				+ "<tr th:each=\"afs : ${entity.getAttributeFileStorage()}\">"
				+ "<td th:text=\"${afs.name}\"></td>"
				+ "<td th:text=\"${afs.fieldTypeName}\"></td>"
				+ "<td ><img th:src=\"${afs.getImagePath()}\" th:alt=\"${afs.getFileName()}\"/></td>"
				+ "</tr>"
				+ "</table>";
		
		return template;
	}

	public static String buildEditTemplateCode() {
		StringBuilder sb = new StringBuilder();
		sb.append("<div> \n"
				+ "<script src=\"/resource/js/entity.js\" type=\"text/javascript\"></script> \n"
				+ "<form id=\"entityFormId\" name=\"entityForm\" action=\"|/app/${client}/entity/save|\" method=\"POST\"> \n"
				+ "<input type=\"hidden\" th:value=\"${entity.entityTypeId}\" id=\"entityTypeId\" name=\"entityTypeId\" /> \n"
				+ "<input type=\"hidden\" th:value=\"${entity.entityId}\" id=\"eId\" name=\"entityId\"/> \n"
				+ "<input type=\"hidden\" id=\"aId\" name=\"aId\" value=\"\"/> \n"
				+ "<input type=\"hidden\" id=\"date\" name=\"date\" value=\"\"/> \n"
				+ "<input type=\"hidden\" id=\"time\" name=\"time\" value=\"\"/> \n"
				+ "<input type=\"hidden\" id=\"wyswyg\" name=\"wyswyg\" value=\"\"/> \n"
				+ "<input type=\"hidden\" id=\"client\" th:value=\"${client}\"/> \n"
				+ "<input type=\"hidden\" id=\"entityId\" th:value=\"${entity.entityId}\"/> \n"
				+ "<input type=\"hidden\" id=\"baseEntityIdToRelateNew\" name=\"baseEntityIdToRelateNew\" th:value=\"${baseEntityIdToRelateNew}\"/> \n"
				+ "<input type=\"hidden\" id=\"newEntityRelationName\" name=\"newEntityRelationName\" th:value=\"${newEntityRelationName}\"/> \n"
				+ "<input type=\"hidden\" id =\"page\" name=\"page\" value=\"addent\"/> \n"
				+ "<input type=\"hidden\" id =\"entityType_id\" name=\"entityType_id\" th:value=\"${entity.entityType.id}\"/> \n"
				+ "<input type=\"hidden\" id=\"entityValid\" name=\"entityValid\" value=\"\"/> \n"
				+ "<table> \n"
					+ "<tr th:each=\" avs,iterStat : ${entity.attributeValueStorage}\"> \n"
						+ "<td th:text=\"${avs.getName()} \"></td> \n"
						+ "<td th:switch=\"${avs.dataTypeName}\"> \n"
							+ "<div th:case=\"${DATATYPE['varchar']}\"> \n"
								+ "<div th:switch=\"${avs.fieldTypeName}\"> \n"
									+ "<div th:case=\"${FIELDTYPE['image']}\"> \n"
										+ "<div th:if=\"${entity.getAttributeFileStorage() != null}\"> \n"
											+ "<div th:each=\"afs : ${entity.getAttributeFileStorage()}\"> \n"
												+ "<div th:if=\"${avs.id == afs.id}\"> \n"
													+ "<a href=\"#\"><img th:src=\"${afs.imagePath}\" alt=\"\" height=\"100mm\" width=\"200mm\"/></a> \n"
												+ "</div> \n"
											+ "</div> \n"
										+ "</div> \n"
									+ "</div> \n"
									+ "<div th:case=\"${FIELDTYPE['file']}\"> \n"
										+ "<div th:text=\"${avs.getValue()}\"></div> \n"
									+ "</div> \n"
									+ "<div th:case=\"${FIELDTYPE['password']}\"> \n"
										+ "<input type=\"password\" th:value=\"${avs.getValue()}\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].valueVarchar'\" onchange=\"addValueAutoSave('text',this.id);\" /> \n"
									+ "</div> \n"
									+ "<div th:case=\"*\"> \n"
										+ "<input type=\"text\" th:value=\"${avs.getValue()}\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].valueVarchar'\" onchange=\"addValueAutoSave('text',this.id);\" /> \n"
									+ "</div> \n"
								+ "</div> \n"
							+ "</div> \n"
							+ "<div th:case=\"${DATATYPE['long']}\"> \n"
								+ "<input type=\"text\" th:value=\"${avs.getValue()}\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].value_Long'\" onchange=\"addValueAutoSave('number',this.id);\"/> \n"
							+ "</div> \n"
							+ "<div th:case=\"${DATATYPE['date']}\"> \n"
								+ "<input type=\"text\" dojoType=\"dijit.form.DateTextBox\" th:value=\"${#dates.format(avs.getValueDate(), 'yyyy-MM-dd')}\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].value_Date'\"  onchange=\"addValueAutoSave('date',this.id);\"/> \n"
							+ "</div> \n"
							+ "<div th:case=\"${DATATYPE['time']}\"> \n"
								+ "<input type=\"text\" th:value=\"|T${avs.getValue()}|\" data-dojo-type=\"dijit/form/TimeTextBox\" constraints=\"{timePattern:'hh:mm a'}\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].value_Time'\"  onchange=\"addValueAutoSave('time',this.id);\"/> \n"
							+ "</div> \n"
							+ "<div th:case=\"${DATATYPE['text']}\"> \n"
								+ "<div th:switch=\"${avs.fieldTypeName}\"> \n"
									+ "<div th:case=\"${FIELDTYPE['WYSIWYG']}\"> \n"
										+ "<textarea th:id=\"${avs.id}\" class=\"claro\" th:text=\"${avs.getValueText()}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].valueText'\"  onchange=\"addValueAutoSave('WYSIWYG',this.id);\" data-dojo-type =\"dijit.Editor\" data-dojo-props=\"extraPlugins:['prettyprint','pagebreak','showblocknodes','preview','save','toolbarlinebreak','normalizeindentoutdent','breadcrumb','findreplace','pastefromword','insertanchor','collapsibletoolbar','foreColor', 'hiliteColor','blockquote','smiley','uploadImage']\"></textarea>"
									+ "</div> \n"
									+ "<div th:case=\"*\"> \n"
										+ "<textarea th:text=\"${avs.getValue()}\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].valueText'\"  onchange=\"addValueAutoSave('text',this.id);\"></textarea> \n"
									+ "</div> \n"
								+ "</div> \n"							
							+ "</div> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].id'\" th:value=\"${avs.id}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].name'\" th:value=\"${avs.name}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].entityTypeId'\" th:value=\"${avs.entityTypeId}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].dataTypeId'\" th:value=\"${avs.dataTypeId}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].fieldTypeId'\" th:value=\"${avs.fieldTypeId}\" /> \n"
						+ "<div th:if=\"${avs.regex != null}\" > \n"
							+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].regex.regexId'\" th:value=\"${avs.regex.regexId}\" /> \n"
							+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].regex.pattern'\" th:value=\"${avs.regex.pattern}\" /> \n"
						+ "</div> \n"
						+ "<div th:if=\"${avs.regex == null}\" > \n"
							+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].regex.regexId'\" value=\"0\" /> \n"
							+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].regex.pattern'\" value=\"\" /> \n"
						+ "</div> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].required'\" th:value=\"${avs.required}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].attributeValueId'\" th:value=\"${avs.attributeValueId}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].dataTypeName'\" th:value=\"${avs.dataTypeName}\" /> \n"
						+ "<input type=\"hidden\" th:id=\"${avs.id}\" th:name=\"'attributeValueStorage['+${iterStat.index}+'].fieldTypeName'\" th:value=\"${avs.fieldTypeName}\" /> \n"
						+ "</td> \n"
					+ "</tr> \n"
				+ "</table> \n"
				+ "</form> \n"
				+ "</div> \n");
		return sb.toString();
	}

}
